spring:
  profiles:
    active: local

  mybatis:
    mapper-locations: classpath:/mappers/*.xml
    type-aliases-package: com.flab.coongyaboard.domain
    configuration:
      map-underscore-to-camel-case: true
      default-statement-timeout: 5
